spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_si
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      connection:
        isolation: 8
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
